classDiagram
    note "Modelo Polimórfico de IPR (Omega v2.6.0)"
    direction BT
    
    class IPR {
        <<Abstract>>
        +String nombre
        +String codigo_bip
        +Monto costo_total
        +Phase fase_actual
        +Estado estado_evaluacion
        +Fondo fondo_financiamiento
        +Via via_evaluacion
    }

    class PROYECTO {
        <<Subtype: Capital>>
        +Subtitulo [31, 33]
        +Boolean crea_activo = true
        +VidaUtil vida_util
        +MetodoEvaluacion [Costo-Beneficio, Costo-Eficiencia]
    }
    
    class PROGRAMA {
        <<Subtype: Corriente>>
        +Subtitulo [24]
        +Boolean crea_activo = false
        +String poblacion_objetivo
        +MetodoEvaluacion [MML, Costo-Efectividad]
    }

    PROYECTO --|> IPR : es un
    PROGRAMA --|> IPR : es un

    %% Clases Específicas de Mecanismos (Poly-IPR)
    class MEC_SNI {
        <<Instance: Proyecto>>
        +codigo_bip: String
        +rate_mdsf: Enum(RS, FI, OT)
        +etapa_bip: Enum(Perfil, Factibilidad, Ejecucion)
        +sector: String
    }

    class MEC_C33 {
        <<Instance: Proyecto>>
        +categoria: Enum(ANF, Conservacion, Emergencia)
        +vida_util_residual: Integer
        +informe_tecnico_favorable: Bool
        +cofinanciamiento_anf: Percentage
    }

    class MEC_FRIL {
        <<Instance: Proyecto>>
        +tipo_fril: Enum(Infraestructura, Emergencia)
        +cumple_norma_5k_utm: Bool
        +res_subdere: String
        +plazo_licitacion: Integer
    }

    class MEC_GLOSA06 {
        <<Instance: Programa>>
        +modelo_gestion: Enum(Ejecucion_Directa)
        +fase_eval_central: Enum(Perfil, Diseno)
        +rate_ses: Enum(RF, OT, FI)
        +gasto_admin_max: Percentage
    }

    class MEC_TRANSFER {
        <<Instance: Programa>>
        +modelo_gestion: Enum(Transferencia)
        +convenio_mandato: Bool
        +itf_gore: Bool
        +gasto_honorario_max: Percentage
    }

    class MEC_FRPD {
        <<Instance: Mixto>>
        +eje_fomento: String
        +nivel_trl: Integer
        +admisibilidad_tecnica: Bool
        +innovacion_ctci: Bool
    }

    class MEC_SUBV8 {
        <<Instance: Programa>>
        +fondo_tematico: Enum(Cultura, Deporte, Social...)
        +puntaje_evaluacion: Float
        +asignacion_directa: Bool
        +antiguedad_organizacion: Integer
    }

    %% Relaciones de Implementación (Realization)
    MEC_SNI ..|> PROYECTO : implementa
    MEC_FRIL ..|> PROYECTO : implementa
    MEC_C33 ..|> PROYECTO : implementa
    
    MEC_GLOSA06 ..|> PROGRAMA : implementa
    MEC_TRANSFER ..|> PROGRAMA : implementa
    MEC_SUBV8 ..|> PROGRAMA : implementa
    MEC_FRPD ..|> IPR : implementa (híbrido)