-- ══════════════════════════════════════════════════════════════════════════════
-- MAPEO DE ROLES LEGACY → CANÓNICOS
-- Generated: 2026-01-05
-- Mapeos: 297 legacy → ~75 canónicos
-- ══════════════════════════════════════════════════════════════════════════════

-- ═══ GORE (Autoridad Regional) ═══
INSERT INTO role_mapping VALUES ('ROL-GOBERNADOR', 'ROL-GORE-GOBERNADOR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-JEFE-GABINETE', 'ROL-GORE-GABINETE', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-PAS', 'ROL-GORE-GOBERNADOR', NULL, 'Sujeto Pasivo = Gobernador');
INSERT INTO role_mapping VALUES ('ROL-EJEC-SEC-CORE', 'ROL-GORE-SEC-CORE', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-EJEC-SEC-COM', 'ROL-GORE-SEC-CORE', NULL, 'Secretario de Comisión');

-- ═══ DAF (Administración y Finanzas) ═══
INSERT INTO role_mapping VALUES ('ROL-JEFE-JURIDICA', 'ROL-DAF-JEFE', NULL, 'También aplica a Jefe Jurídica');
INSERT INTO role_mapping VALUES ('ROL-GESTION-JEFE', 'ROL-DAF-JEFE', NULL, 'Jefe de División genérico');
INSERT INTO role_mapping VALUES ('ROL-PROFESIONAL-DAF', 'ROL-DAF-PROFESIONAL', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-PROF', 'ROL-DAF-PROFESIONAL', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-FIN-CONT', 'ROL-DAF-CONTADOR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-FIN-ANALISTA-CON', 'ROL-DAF-ANALISTA', 'CONTABLE', NULL);
INSERT INTO role_mapping VALUES ('ROL-FIN-ANALISTA-PRE', 'ROL-DAF-ANALISTA', 'PRESUPUESTO', NULL);
INSERT INTO role_mapping VALUES ('ROL-FIN-ANALISTA-TES', 'ROL-DAF-ANALISTA', 'TESORERIA', NULL);
INSERT INTO role_mapping VALUES ('ROL-FIN-ANALISTA-COM', 'ROL-DAF-ANALISTA', 'COMPRAS', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-MOD', 'ROL-DAF-ANALISTA', 'PRESUPUESTO', 'Modificaciones presupuestarias');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-VIA', 'ROL-DAF-ANALISTA', 'VIATICOS', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-HON', 'ROL-DAF-ANALISTA', 'HONORARIOS', NULL);
INSERT INTO role_mapping VALUES ('ROL-FIN-JEFE-DEPTO-C', 'ROL-DAF-JEFE-DEPTO', NULL, 'Contabilidad');
INSERT INTO role_mapping VALUES ('ROL-FIN-JEFE-DEPTO-P', 'ROL-DAF-JEFE-DEPTO', NULL, 'Presupuesto');
INSERT INTO role_mapping VALUES ('ROL-FIN-JEFE-DEPTO-T', 'ROL-DAF-JEFE-DEPTO', NULL, 'Tesorería');
INSERT INTO role_mapping VALUES ('ROL-BACK-RRHH-JEFE', 'ROL-DAF-JEFE-DEPTO', NULL, 'RRHH');
INSERT INTO role_mapping VALUES ('ROL-GESTION-JEFE-RRHH', 'ROL-DAF-JEFE-DEPTO', NULL, 'RRHH');
INSERT INTO role_mapping VALUES ('ROL-BACK-OPS-BOD', 'ROL-DAF-ENCARGADO', 'BODEGA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-OPS-AF', 'ROL-DAF-ENCARGADO', 'ACTIVOS', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-FIN-REND', 'ROL-DAF-ENCARGADO', 'RENDICIONES', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-OPS-FLOTA', 'ROL-DAF-ENCARGADO', 'FLOTA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-RH-REM', 'ROL-DAF-ENCARGADO', 'REMUNERACIONES', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-PER-BIEN', 'ROL-DAF-BIENESTAR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-BIE', 'ROL-DAF-BIENESTAR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-FIN-SOCIO-BIEN', 'ROL-DAF-BIENESTAR', NULL, 'Socio del servicio');
INSERT INTO role_mapping VALUES ('ROL-FIN-ABS-COMP', 'ROL-DAF-COMPRADOR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-ENCARGADO-CALIDAD', 'ROL-STAFF-CALIDAD', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ENC', 'ROL-DAF-ENCARGADO', 'ACTIVOS', 'Encargado Activos/Calidad');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CONDUCTOR', 'ROL-DAF-ENCARGADO', 'FLOTA', 'Conductor institucional');
INSERT INTO role_mapping VALUES ('ROL-BACK-AUXILIAR', 'ROL-DAF-PROFESIONAL', NULL, 'Apoyo logístico');
INSERT INTO role_mapping VALUES ('ROL-BACK-PER-GEST', 'ROL-DAF-PROFESIONAL', NULL, 'Gestor de Personas');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-CAP', 'ROL-DAF-PROFESIONAL', NULL, 'Capacitación');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-CIC', 'ROL-DAF-PROFESIONAL', NULL, 'Ciclo de Vida');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-SER', 'ROL-DAF-PROFESIONAL', NULL, 'Servicios Generales');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ENC-SERV', 'ROL-DAF-PROFESIONAL', NULL, 'Servicios Generales');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PER-FUN', 'ROL-DAF-PROFESIONAL', NULL, 'Funcionario genérico');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PER-JUN', 'ROL-DAF-PROFESIONAL', NULL, 'Junta Calificadora');
INSERT INTO role_mapping VALUES ('ROL-GESTION-SECRETARIA-D', 'ROL-DAF-PROFESIONAL', NULL, 'Secretaria de División');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FIN-UCR', 'ROL-DAF-ANALISTA', 'RENDICIONES', 'Unidad Control Rendiciones');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FIN-COGIR', 'ROL-DAF-ANALISTA', 'TESORERIA', 'Cogirador Autorizado');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FINOPS', 'ROL-DAF-ANALISTA', 'PRESUPUESTO', 'FinOps Manager');

-- ═══ JUR (Jurídica) ═══
INSERT INTO role_mapping VALUES ('ROL-NORM-ABOG', 'ROL-JUR-ABOGADO', 'INFORMANTE', NULL);
INSERT INTO role_mapping VALUES ('ROL-NORM-ABOGADO-CONV', 'ROL-JUR-ABOGADO', 'CONVENIOS', NULL);
INSERT INTO role_mapping VALUES ('ROL-NORM-ABOGADO-LICI', 'ROL-JUR-ABOGADO', 'LICITACIONES', NULL);
INSERT INTO role_mapping VALUES ('ROL-NORM-ABOGADO-GENE', 'ROL-JUR-ABOGADO', NULL, 'Abogado General');
INSERT INTO role_mapping VALUES ('ROL-NORM-JUR', 'ROL-JUR-ABOGADO', 'DAF', NULL);
INSERT INTO role_mapping VALUES ('ROL-NORM-JUD', 'ROL-JUR-ABOGADO', 'JUDICIALES', NULL);
INSERT INTO role_mapping VALUES ('ROL-NORM-DISC', 'ROL-JUR-ABOGADO', 'DISCIPLINARIOS', NULL);
INSERT INTO role_mapping VALUES ('ROL-NORM-REV', 'ROL-JUR-ABOGADO', 'REVISOR', NULL);
INSERT INTO role_mapping VALUES ('ROL-JUR-ASES-DIV', 'ROL-JUR-ABOGADO', NULL, 'Asesor de División');
INSERT INTO role_mapping VALUES ('ROL-NORM-FIS', 'ROL-JUR-FISCAL', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-MFE', 'ROL-JUR-MINISTRO-FE', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-NORM-LOBBY', 'ROL-JUR-ABOGADO', NULL, 'Encargado Ley de Lobby');

-- ═══ TIC (Tecnología) ═══
INSERT INTO role_mapping VALUES ('ROL-TDE-JEFE-TI', 'ROL-TIC-JEFE', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-DESARROLLADO', 'ROL-TIC-DESARROLLADOR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-DEV-BACK', 'ROL-TIC-DESARROLLADOR', 'BACKEND', 'Lead Developer');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FRONT', 'ROL-TIC-DESARROLLADOR', 'FRONTEND', NULL);
INSERT INTO role_mapping VALUES ('ROL-DEV-TIC-DEV', 'ROL-TIC-DESARROLLADOR', 'DEVOPS', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-NEW', 'ROL-TIC-DESARROLLADOR', NULL, 'Nuevo Desarrollador');
INSERT INTO role_mapping VALUES ('ROL-DEV-QA', 'ROL-TIC-DESARROLLADOR', 'QA', NULL);
INSERT INTO role_mapping VALUES ('ROL-DEV-QA-ANALISTA', 'ROL-TIC-DESARROLLADOR', 'QA', NULL);
INSERT INTO role_mapping VALUES ('ROL-DEV-ARCH-DATOS', 'ROL-TIC-DESARROLLADOR', 'DATOS', 'Arquitecto de Datos');
INSERT INTO role_mapping VALUES ('ROL-DEV-ARQ-CAT', 'ROL-TIC-DESARROLLADOR', 'DATOS', 'Arquitecto Categórico');
INSERT INTO role_mapping VALUES ('ROL-GESTION-LEAD', 'ROL-TIC-DESARROLLADOR', NULL, 'Líder Técnico');
INSERT INTO role_mapping VALUES ('ROL-GESTION-SYS', 'ROL-TIC-DESARROLLADOR', NULL, 'Desarrollador de Sistema');
INSERT INTO role_mapping VALUES ('ROL-OPS-TIC-PLAT', 'ROL-TIC-ADMIN', 'PLATAFORMA', NULL);
INSERT INTO role_mapping VALUES ('ROL-OPS-GEONODO', 'ROL-TIC-ADMIN', 'GEONODO', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-DBA', 'ROL-TIC-ADMIN', 'BD', NULL);
INSERT INTO role_mapping VALUES ('ROL-OPS-ADMIN-SYS', 'ROL-TIC-ADMIN', 'SISTEMAS', NULL);
INSERT INTO role_mapping VALUES ('ROL-ADMIN-TI', 'ROL-TIC-ADMIN', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-CISO', 'ROL-TIC-CISO', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-TDE-CISO', 'ROL-TIC-CISO', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-EJEC-CPER-SEC', 'ROL-TIC-CISO', NULL, 'CISO/Desarrollador');
INSERT INTO role_mapping VALUES ('ROL-GESTION-TIC-SRE', 'ROL-TIC-SRE', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-TIC-CTD', 'ROL-TIC-CTD', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-CTD', 'ROL-TIC-CTD', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-TIC-MESA', 'ROL-TIC-MESA', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-KODA', 'ROL-TIC-AGENTE-KODA', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-NORM-AUDIT', 'ROL-TIC-AGENTE-AUDIT', NULL, 'Fiscalizador Bot');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CLASIF', 'ROL-TIC-AGENTE-CLASIF', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-MORA', 'ROL-TIC-AGENTE-MONITOR', NULL, 'Mora Watcher');
INSERT INTO role_mapping VALUES ('ROL-GESTION-JANO', 'ROL-TIC-AGENTE-KODA', NULL, 'Asesor Jurídico IA');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CERT', 'ROL-TIC-AGENTE-KODA', NULL, 'Robot Cert-Manager');
INSERT INTO role_mapping VALUES ('ROL-OPS-MIGRADOR', 'ROL-TIC-DESARROLLADOR', 'DATOS', 'Ingeniero de Migración');
INSERT INTO role_mapping VALUES ('ROL-OPS-PISEE', 'ROL-TIC-ADMIN', NULL, 'Operador PISEE');
INSERT INTO role_mapping VALUES ('ROL-OPS-ENCARGADO-IN', 'ROL-TIC-ADMIN', NULL, 'Encargado Interoperabilidad');
INSERT INTO role_mapping VALUES ('ROL-OPS-ENCARGADO-CO', 'ROL-TIC-ADMIN', NULL, 'Encargado Continuidad');
INSERT INTO role_mapping VALUES ('ROL-TDE-PLATFORM-ENG', 'ROL-TIC-ADMIN', NULL, 'Encargado TI Municipal');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PRES', 'ROL-TIC-AGENTE-KODA', NULL, 'Presidente Subcomité IA');
INSERT INTO role_mapping VALUES ('ROL-PRESIDENTE-SUBCOMITE-IA', 'ROL-TIC-AGENTE-KODA', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-KB', 'ROL-TIC-DESARROLLADOR', 'DATOS', 'Knowledge Engineer');
INSERT INTO role_mapping VALUES ('ROL-GESTION-DPO', 'ROL-TIC-CISO', NULL, 'DPO Protección Datos');
INSERT INTO role_mapping VALUES ('ROL-GESTION-APD', 'ROL-TIC-AGENTE-KODA', NULL, 'Agencia Protección Datos');
INSERT INTO role_mapping VALUES ('ROL-ESPECIALISTA-BI', 'ROL-TIC-DESARROLLADOR', 'DATOS', 'Especialista BI');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PO', 'ROL-TIC-DESARROLLADOR', NULL, 'Product Owner');

-- ═══ DIPLADE (Planificación y Desarrollo) ═══
INSERT INTO role_mapping VALUES ('ROL-TERR-ANALISTA-TER', 'ROL-DIPLADE-TERRITORIAL', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-TERR-TERR', 'ROL-DIPLADE-TERRITORIAL', NULL, 'Analista Equidad Territorial');
INSERT INTO role_mapping VALUES ('ROL-TERR-TERR-SOC', 'ROL-DIPLADE-TERRITORIAL', NULL, 'Sociólogo Territorial');
INSERT INTO role_mapping VALUES ('ROL-TERR-PLAN', 'ROL-DIPLADE-ANALISTA', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-TERR-URB', 'ROL-DIPLADE-URBANO', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-JEFE-ESTUDIO', 'ROL-DIPLADE-ESTUDIOS', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-250-ENC', 'ROL-DIPLADE-ANALISTA', NULL, 'Agenda Ñuble 250');
INSERT INTO role_mapping VALUES ('ROL-GESTION-OBS', 'ROL-DIPLADE-ANALISTA', NULL, 'Observatorio Regional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-IDE', 'ROL-DIPLADE-TERRITORIAL', NULL, 'Coordinador IDE');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PROPIR', 'ROL-DIPLADE-ANALISTA', NULL, 'Coordinador PROPIR');

-- ═══ DIPIR (Presupuesto e Inversión) ═══
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-EVA', 'ROL-DIPIR-ANALISTA', 'EVALUACION', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANAL-INV', 'ROL-DIPIR-ANALISTA', 'PREINVERSION', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-DAE-PRE', 'ROL-DIPIR-ANALISTA', 'PREINVERSION', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-PPR', 'ROL-DIPIR-ANALISTA', 'PPR', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-INV-SEG', 'ROL-DIPIR-ANALISTA', 'SEGUIMIENTO', 'Sistema de monitoreo');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-CAR', 'ROL-DIPIR-ANALISTA', 'CARTERA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-JEFE-PROGRAM', 'ROL-DIPIR-ANALISTA', 'CARTERA', 'Jefe Programación');
INSERT INTO role_mapping VALUES ('ROL-EJEC-URAI-EJEC', 'ROL-DIPIR-ITO', 'PROGRAMAS', NULL);
INSERT INTO role_mapping VALUES ('ROL-EJEC-INFRA-ITO', 'ROL-DIPIR-ITO', 'OBRAS', NULL);
INSERT INTO role_mapping VALUES ('ROL-EJEC-ITO-MUN', 'ROL-DIPIR-ITO', 'OBRAS', 'ITO Municipal');
INSERT INTO role_mapping VALUES ('ROL-EJEC-ITO', 'ROL-DIPIR-ITO', NULL, 'ITO externo');
INSERT INTO role_mapping VALUES ('ROL-EJEC-ITP', 'ROL-DIPIR-ITO', 'PROGRAMAS', NULL);
INSERT INTO role_mapping VALUES ('ROL-OPS-C33', 'ROL-DIPIR-C33', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-FOND-EVAL', 'ROL-DIPIR-ANALISTA', 'EVALUACION', 'Evaluador Social');
INSERT INTO role_mapping VALUES ('ROL-GESTION-MIEMBRO-COMI', 'ROL-DIPIR-ANALISTA', 'EVALUACION', 'Comité Pertinencia');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FRPD', 'ROL-DIPIR-ANALISTA', NULL, 'Comité FRPD');
INSERT INTO role_mapping VALUES ('ROL-GESTION-RECP', 'ROL-DIPIR-ITO', 'OBRAS', 'Comisión Recepción');
INSERT INTO role_mapping VALUES ('ROL-GESTION-MON', 'ROL-DIPIR-ANALISTA', 'SEGUIMIENTO', 'Monitor de Sistema');
INSERT INTO role_mapping VALUES ('ROL-GESTION-IPR', 'ROL-DIPIR-ANALISTA', NULL, 'Asesor IPR');

-- ═══ DIDESO (Desarrollo Social y Humano) ═══
INSERT INTO role_mapping VALUES ('ROL-GESTION-G7-FORM', 'ROL-DIDESO-G7', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANAL8', 'ROL-DIDESO-8PORC', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-PMG-GEN', 'ROL-DIDESO-GENERO', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-DEP', 'ROL-DIDESO-ANALISTA', 'DEPORTE', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-CUL', 'ROL-DIDESO-ANALISTA', 'CULTURA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-SAL', 'ROL-DIDESO-ANALISTA', 'SALUD', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-EDU', 'ROL-DIDESO-ANALISTA', 'EDUCACION', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-VIV', 'ROL-DIDESO-ANALISTA', 'VIVIENDA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-SOC', 'ROL-DIDESO-ANALISTA', NULL, 'Analista Social');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ORG-POST', 'ROL-EXT-ORGANIZACION', NULL, 'Organización postulante 8%');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ORG-BEN', 'ROL-EXT-ORGANIZACION', NULL, 'Organización beneficiaria');

-- ═══ DIFOI (Fomento e Industria) ═══
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-TUR', 'ROL-DIFOI-ANALISTA', 'TURISMO', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-PES', 'ROL-DIFOI-ANALISTA', 'PESCA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-MED', 'ROL-DIFOI-ANALISTA', 'MEDIO-AMBIENTE', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-ENE', 'ROL-DIFOI-ANALISTA', 'ENERGIA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-AGU', 'ROL-DIFOI-ANALISTA', NULL, 'Agua Potable Rural');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CTI-PROF', 'ROL-DIFOI-CTI', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-ANALISTA-PATROCINANTE-DIFOI', 'ROL-DIFOI-PATROCINANTE', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-CAMP', 'ROL-DIFOI-ANALISTA', NULL, 'Equipo Campeón');

-- ═══ DIINF (Infraestructura y Transporte) ═══
INSERT INTO role_mapping VALUES ('ROL-ANALISTA-CONECTIVIDAD', 'ROL-DIINF-ANALISTA', 'CONECTIVIDAD', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-CON-ING', 'ROL-DIINF-INGENIERO', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-DEV-ARQ', 'ROL-DIINF-ARQUITECTO', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-UOCT', 'ROL-DIINF-ANALISTA', 'TRANSPORTE', 'UOCT Regional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-MUN', 'ROL-DIINF-ANALISTA', NULL, 'Analista Municipios');
INSERT INTO role_mapping VALUES ('ROL-GESTION-MUNI-ENC', 'ROL-DIINF-ANALISTA', NULL, 'Encargado Municipalidades');

-- ═══ CIES (Centro Emergencias y Seguridad) ═══
INSERT INTO role_mapping VALUES ('ROL-GESTION-UCR-COOR', 'ROL-CIES-COORDINADOR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-COORDINADOR-CIES', 'ROL-CIES-COORDINADOR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SUP', 'ROL-CIES-SUPERVISOR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-ENL', 'ROL-CIES-ENLACE', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-EVID', 'ROL-CIES-CUSTODIO', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-SEG-ASES', 'ROL-CIES-SUPERVISOR', NULL, 'Asesor Técnico Seguridad');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PREV', 'ROL-CIES-SUPERVISOR', NULL, 'Encargado Prevención');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PREV-ANAL', 'ROL-CIES-SUPERVISOR', NULL, 'Analista Prevención');
INSERT INTO role_mapping VALUES ('ROL-GESTION-GRD', 'ROL-CIES-COORDINADOR', NULL, 'Comité GRD');

-- ═══ STAFF (Apoyo Directo) ═══
INSERT INTO role_mapping VALUES ('ROL-GESTION-OF', 'ROL-STAFF-PARTES', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-TRANSP', 'ROL-STAFF-TRANSPARENCIA', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-TRANSP-REF', 'ROL-STAFF-TRANSPARENCIA', NULL, 'Referente por ítem');
INSERT INTO role_mapping VALUES ('ROL-GESTION-OIRS', 'ROL-STAFF-OIRS', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-AUD', 'ROL-STAFF-AUDITORIA', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-AUDITOR-EXTE', 'ROL-EXT-CGR', NULL, 'Auditor Externo');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PER', 'ROL-STAFF-COMUNICACIONES', NULL, 'Periodista');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FOTO', 'ROL-STAFF-COMUNICACIONES', NULL, 'Fotógrafo');
INSERT INTO role_mapping VALUES ('ROL-GESTION-COM', 'ROL-STAFF-COMUNICACIONES', NULL, 'Encargado Comunicaciones');
INSERT INTO role_mapping VALUES ('ROL-GESTION-COMUNICON', 'ROL-STAFF-COMUNICACIONES', NULL, 'Asesor Comunicacional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CTRL', 'ROL-STAFF-AUDITORIA', NULL, 'Encargado Control Gestión');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ENCARGADO-CO', 'ROL-STAFF-AUDITORIA', NULL, 'Comité Paritario');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PREVENCIONIS', 'ROL-STAFF-AUDITORIA', NULL, 'Prevencionista Riesgos');
INSERT INTO role_mapping VALUES ('ROL-GESTION-VERDE-MEMB', 'ROL-STAFF-CALIDAD', NULL, 'Comité Estado Verde');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ENCARGADO-ES', 'ROL-STAFF-CALIDAD', NULL, 'Encargado Estado Verde');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ENCARGADO-CA', 'ROL-STAFF-CALIDAD', NULL, 'Capacitación Digital');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PMG-TD', 'ROL-STAFF-CALIDAD', NULL, 'Referente PMG TDE');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PMG-GASTO', 'ROL-STAFF-CALIDAD', NULL, 'Referente Concentración Gasto');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PMG-PSICO', 'ROL-STAFF-CALIDAD', NULL, 'Referente Riesgos Psicosociales');
INSERT INTO role_mapping VALUES ('ROL-GESTION-MEMB', 'ROL-STAFF-CALIDAD', NULL, 'Miembro Comité TDE');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FNX-J', 'ROL-STAFF-AUDITORIA', NULL, 'Jefe Unidad FENIX');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FNX-FIN', 'ROL-STAFF-AUDITORIA', NULL, 'Interventor Financiero FENIX');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FNX-OP', 'ROL-STAFF-AUDITORIA', NULL, 'Interventor FENIX');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ARCHIVO', 'ROL-STAFF-PARTES', NULL, 'Encargado Archivo');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ARCH', 'ROL-STAFF-PARTES', NULL, 'Archivero Digital');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANALISTA-CASIS', 'ROL-TIC-AGENTE-KODA', NULL, 'Control Asistencia');

-- ═══ EXT (Stakeholders Externos) ═══
-- SEREMIs
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-EDU', 'ROL-EXT-SEREMI', 'EDUCACION', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-SALUD', 'ROL-EXT-SEREMI', 'SALUD', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-VIV', 'ROL-EXT-SEREMI', 'VIVIENDA', NULL);
INSERT INTO role_mapping VALUES ('ROL-EJEC-SEREMI-MOP', 'ROL-EXT-SEREMI', 'OBRAS-PUBLICAS', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-AGRI', 'ROL-EXT-SEREMI', 'AGRICULTURA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-ECO', 'ROL-EXT-SEREMI', 'ECONOMIA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-TRAB', 'ROL-EXT-SEREMI', 'TRABAJO', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-MEDIO', 'ROL-EXT-SEREMI', 'MEDIO-AMBIENTE', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-MUJER', 'ROL-EXT-SEREMI', 'MUJER', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-GOB', 'ROL-EXT-SEREMI', 'GOBIERNO', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-HAC', 'ROL-EXT-SEREMI', 'HACIENDA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI-CULT', 'ROL-EXT-SEREMI', 'CULTURAS', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SEREMI_SECTORIAL', 'ROL-EXT-SEREMI', NULL, 'SEREMI genérico');

-- Municipios
INSERT INTO role_mapping VALUES ('ROL-GESTION-ALC', 'ROL-EXT-MUNICIPIO', 'ALCALDE', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SECPLA', 'ROL-EXT-MUNICIPIO', 'SECPLA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SECPLA-CHILL', 'ROL-EXT-MUNICIPIO', 'SECPLA', 'Chillán');
INSERT INTO role_mapping VALUES ('ROL-GESTION-SECPLA-SAN-C', 'ROL-EXT-MUNICIPIO', 'SECPLA', 'San Carlos');
INSERT INTO role_mapping VALUES ('ROL-EJEC-DOM', 'ROL-EXT-MUNICIPIO', 'DOM', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-UTM-GENERICA', 'ROL-EXT-MUNICIPIO', 'UTM', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-TEC', 'ROL-EXT-MUNICIPIO', NULL, 'Desarrollador UT Municipal');
INSERT INTO role_mapping VALUES ('ROL-GESTION-DIG', 'ROL-EXT-MUNICIPIO', NULL, 'Encargado TDE Municipal');

-- CGR y Control
INSERT INTO role_mapping VALUES ('ROL-GESTION-CGR', 'ROL-EXT-CGR', NULL, 'Analista Toma de Razón');
INSERT INTO role_mapping VALUES ('ROL-GESTION-TRIB-CUENTA', 'ROL-EXT-CGR', NULL, 'Juez de Cuentas');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CAIGG', 'ROL-EXT-CGR', NULL, 'Auditor General de Gobierno');
INSERT INTO role_mapping VALUES ('ROL-GESTION-AUD-MIN', 'ROL-EXT-CGR', NULL, 'Auditor Ministerial');

-- MDSF y DIPRES
INSERT INTO role_mapping VALUES ('ROL-GESTION-MDS', 'ROL-EXT-MDSF', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-DIPRES', 'ROL-EXT-DIPRES', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SUBDERE', 'ROL-EXT-SUBDERE', NULL, NULL);

-- Ciudadanos y Organizaciones
INSERT INTO role_mapping VALUES ('ROL-CIUDADANO', 'ROL-EXT-CIUDADANO', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-EXT', 'ROL-EXT-CIUDADANO', NULL, 'Usuario Externo');
INSERT INTO role_mapping VALUES ('ROL-GESTION-BENEFICIARIO', 'ROL-EXT-CIUDADANO', NULL, 'Beneficiario Individual');
INSERT INTO role_mapping VALUES ('ROL-GESTION-DIRIGENTE-SO', 'ROL-EXT-ORGANIZACION', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-JJVV', 'ROL-EXT-ORGANIZACION', NULL, 'Junta de Vecinos');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ONG', 'ROL-EXT-ORGANIZACION', NULL, 'ONG/Fundación');
INSERT INTO role_mapping VALUES ('ROL-GESTION-COSOC', 'ROL-EXT-ORGANIZACION', NULL, 'COSOC');

-- Ejecutores
INSERT INTO role_mapping VALUES ('ROL-EJEC-DIR', 'ROL-EXT-EJECUTOR', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-EJEC-ANAL', 'ROL-EXT-EJECUTOR', NULL, 'Analista Ejecutor');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CORPORACION-', 'ROL-EXT-EJECUTOR', NULL, 'Corporación Municipal');
INSERT INTO role_mapping VALUES ('ROL-GESTION-EQ', 'ROL-EXT-EJECUTOR', NULL, 'Trabajador Corporación');

-- Instituciones Externas
INSERT INTO role_mapping VALUES ('ROL-GESTION-CONAF', 'ROL-EXT-INSTITUCION', 'CONAF', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-PDI', 'ROL-EXT-INSTITUCION', 'PDI', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-BOMB', 'ROL-EXT-INSTITUCION', 'BOMBEROS', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-CARAB', 'ROL-EXT-INSTITUCION', 'CARABINEROS', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SENAPRED', 'ROL-EXT-INSTITUCION', 'SENAPRED', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SII', 'ROL-EXT-INSTITUCION', 'SII', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SAG', 'ROL-EXT-INSTITUCION', 'SAG', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SERNATUR', 'ROL-EXT-INSTITUCION', 'SERNATUR', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-CORFO', 'ROL-EXT-INSTITUCION', 'CORFO', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-IND', 'ROL-EXT-INSTITUCION', 'INDAP', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-INDAP', 'ROL-EXT-INSTITUCION', 'INDAP', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SERCO', 'ROL-EXT-INSTITUCION', 'SERCOTEC', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SENCE', 'ROL-EXT-INSTITUCION', 'SENCE', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-FOSIS', 'ROL-EXT-INSTITUCION', 'FOSIS', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-SERVIU', 'ROL-EXT-INSTITUCION', 'SERVIU', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-DGA', 'ROL-EXT-INSTITUCION', 'DGA', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-DOH', 'ROL-EXT-INSTITUCION', 'DOH', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-CNR', 'ROL-EXT-INSTITUCION', 'CNR', NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-JUNJI', 'ROL-EXT-INSTITUCION', NULL, 'JUNJI');
INSERT INTO role_mapping VALUES ('ROL-GESTION-SALUD-SRV', 'ROL-EXT-INSTITUCION', NULL, 'Servicio de Salud');
INSERT INTO role_mapping VALUES ('ROL-GESTION-DIRECTOR_SERVICIO_REGIONAL', 'ROL-EXT-INSTITUCION', NULL, 'Director Servicio Regional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-BC', 'ROL-EXT-INSTITUCION', NULL, 'Banco Central');
INSERT INTO role_mapping VALUES ('ROL-GESTION-SUBTEL', 'ROL-EXT-INSTITUCION', NULL, 'SUBTEL');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANID', 'ROL-EXT-INSTITUCION', NULL, 'ANID');

-- Universidades e Investigación
INSERT INTO role_mapping VALUES ('ROL-GESTION-UNIV', 'ROL-EXT-UNIVERSIDAD', NULL, NULL);
INSERT INTO role_mapping VALUES ('ROL-GESTION-UNIVERSIDAD-', 'ROL-EXT-UNIVERSIDAD', NULL, 'Universidad Regional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CENIC', 'ROL-EXT-UNIVERSIDAD', NULL, 'Centro de Investigación');

-- Gremios y Asociaciones
INSERT INTO role_mapping VALUES ('ROL-GESTION-CAMARA', 'ROL-EXT-GREMIO', NULL, 'Cámara de Comercio');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CPC', 'ROL-EXT-GREMIO', NULL, 'CPC Regional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-SNA', 'ROL-EXT-GREMIO', NULL, 'SNA/SOFO');
INSERT INTO role_mapping VALUES ('ROL-GESTION-SINDIC', 'ROL-EXT-GREMIO', NULL, 'Central Sindical');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CCASOC', 'ROL-EXT-GREMIO', NULL, 'Colegio Profesional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-REP-AMUCH', 'ROL-EXT-GREMIO', NULL, 'AMUCH');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANCORE', 'ROL-EXT-GREMIO', NULL, 'ANCORE');
INSERT INTO role_mapping VALUES ('ROL-GESTION-FEMP', 'ROL-EXT-GREMIO', NULL, 'Federación Municipios');
INSERT INTO role_mapping VALUES ('ROL-GESTION-EMP', 'ROL-EXT-GREMIO', NULL, 'Empresa/Gremio');

-- Otros Externos
INSERT INTO role_mapping VALUES ('ROL-GESTION-DPR', 'ROL-EXT-INSTITUCION', NULL, 'Delegado Presidencial Regional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-DPP', 'ROL-EXT-INSTITUCION', NULL, 'Delegado Presidencial Provincial');
INSERT INTO role_mapping VALUES ('ROL-GESTION-APOYO', 'ROL-GORE-SEC-CORE', NULL, 'Profesional Apoyo CORE');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CDR', 'ROL-EXT-INSTITUCION', NULL, 'Comité Directivo Regional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CSEU-MEMB', 'ROL-EXT-INSTITUCION', NULL, 'Comité CSEU');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CPLT', 'ROL-EXT-INSTITUCION', NULL, 'Consejo Transparencia');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CDE', 'ROL-EXT-INSTITUCION', NULL, 'CDE');
INSERT INTO role_mapping VALUES ('ROL-GESTION-TC', 'ROL-EXT-INSTITUCION', NULL, 'Tribunal Constitucional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CORTE-NUBLE', 'ROL-EXT-INSTITUCION', NULL, 'Corte de Apelaciones');
INSERT INTO role_mapping VALUES ('ROL-GESTION-JUZG-LETRAS', 'ROL-EXT-INSTITUCION', NULL, 'Juzgado de Letras');
INSERT INTO role_mapping VALUES ('ROL-NORM-MP', 'ROL-EXT-INSTITUCION', NULL, 'Ministerio Público');
INSERT INTO role_mapping VALUES ('ROL-GESTION-NOTARIO', 'ROL-EXT-INSTITUCION', NULL, 'Notario Público');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CONSULTOR-EX', 'ROL-EXT-UNIVERSIDAD', NULL, 'Consultor Externo');
INSERT INTO role_mapping VALUES ('ROL-GESTION-CONTRAPARTE-', 'ROL-DAF-PROFESIONAL', NULL, 'Contraparte Interna');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ENCARGADO-CS', 'ROL-STAFF-OIRS', NULL, 'Encargado CSEU');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ENCARGADO-DE', 'ROL-DIPLADE-ANALISTA', NULL, 'Encargado Descentralización');
INSERT INTO role_mapping VALUES ('ROL-GESTION-DIGITRANS', 'ROL-TIC-CTD', NULL, 'Asesor Digitrans');
INSERT INTO role_mapping VALUES ('ROL-GESTION-GOREOLOGO', 'ROL-DIPLADE-ANALISTA', NULL, 'Goreólogo');
INSERT INTO role_mapping VALUES ('ROL-GESTION-INT', 'ROL-STAFF-COMUNICACIONES', NULL, 'Encargado RRII');
INSERT INTO role_mapping VALUES ('ROL-GESTION-MEDIA-COMUNI', 'ROL-EXT-CIUDADANO', NULL, 'Medio de Comunicación');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PRENSA-REGIO', 'ROL-EXT-CIUDADANO', NULL, 'Prensa Regional');
INSERT INTO role_mapping VALUES ('ROL-GESTION-SERNAM', 'ROL-EXT-INSTITUCION', NULL, 'SernamEG');
INSERT INTO role_mapping VALUES ('ROL-GESTION-REZ-ENC', 'ROL-DIPLADE-ANALISTA', NULL, 'Encargado Zonas Rezago');
INSERT INTO role_mapping VALUES ('ROL-GESTION-UNIDAD-COORD', 'ROL-DIPIR-ANALISTA', NULL, 'Unidad Coordinación');
INSERT INTO role_mapping VALUES ('ROL-OPS-TRANS', 'ROL-DIPIR-ANALISTA', NULL, 'Analista Transferencias');
INSERT INTO role_mapping VALUES ('ROL-EXT-CONSEJERO-SEG', 'ROL-EXT-ORGANIZACION', NULL, 'Mesa de Seguridad');
INSERT INTO role_mapping VALUES ('ROL-EXT-PARLAMENTARIO', 'ROL-EXT-INSTITUCION', NULL, 'Parlamentario');
INSERT INTO role_mapping VALUES ('ROL-GENERIC-ANALISTA-BASE', 'ROL-DAF-ANALISTA', NULL, 'Analista Base Arquetipo');
INSERT INTO role_mapping VALUES ('ROL-GESTION-PROFESIONAL_BASE', 'ROL-DAF-PROFESIONAL', NULL, 'Profesional Base Arquetipo');
INSERT INTO role_mapping VALUES ('ROL-GESTION-ANAL', 'ROL-TIC-ADMIN', NULL, 'Analista Informática DIT');
INSERT INTO role_mapping VALUES ('ROL-DEV-HON-JEFE', 'ROL-DAF-JEFE-DEPTO', NULL, 'Jefatura Control Jerárquico');
INSERT INTO role_mapping VALUES ('ROL-OPERADOR-SISTEMA', 'ROL-DAF-PROFESIONAL', NULL, 'Operador de Sistema');

-- ════════════════════════════════════════════════════════════════════
-- VERIFICACIÓN
-- ════════════════════════════════════════════════════════════════════

-- Verificar cobertura
SELECT 
    (SELECT COUNT(*) FROM role_mapping) as roles_mapeados,
    (SELECT COUNT(*) FROM dim_role_canonical) as roles_canonicos,
    (SELECT COUNT(DISTINCT canonical_id) FROM role_mapping) as canonicos_usados;
